Add 2 New Rules for Footnotes
platers/obsidian-linter pull request #40
Opened 2021-09-13 07:20 UTC by chrisgrieser

see issue #39. Also ran `npm run compile` and `npm run lint` this time :)

2021-09-13 07:30 UTC, chrisgrieser commented
I would have added #36 as well, but I do not know how to get the `tabsize` setting.

2021-09-13 10:01 UTC, chrisgrieser commented
added further exceptions for the capitalize rule

2021-09-13 15:01 UTC, platers requested changes

2021-09-13 15:03 UTC, platers commented
> I would have added #36 as well, but I do not know how to get the `tabsize` setting.

You can pass it in as an option, the user can set `tabsize=2` in the settings. See the other rules for examples.

2021-09-13 20:27 UTC, chrisgrieser commented on rules.ts
> -        line with trailing spaces and tabs    				`, // eslint-disable-line no-tabs
I actually didn't intend to? I think that could have happened by accident. (My keyboard is a bit broken, and I often do `undo` to fix stuff, my best guess I accidentally did something. -.-)

2021-09-13 20:27 UTC, chrisgrieser commented on rules.ts
> -
also unintended

2021-09-13 20:28 UTC, chrisgrieser commented on rules.ts
> -
also unintended

2021-09-13 20:42 UTC, chrisgrieser commented on rules.ts
> +          text = text.replace(/\n{3,}/gm, '\n\n'); // remove blank lines resulting from ft removal
see issue #42. 

you are right, it does also remove blank lines, de facto executing `consecutive-blank-lines` when executing rule. Should this be changed not to do that?

2021-09-13 20:49 UTC, chrisgrieser commented on rules.ts
> +      (text: string) => {
I tested the function outside of Obsidian with a text file and it didn't move anything when footnotes are already at the bottom.

How do I conduct such a test with test.ts? The readme states:
> Run `npm run compile` to build, generate documentation, and test the plugin.
I have run `npm run compile` before committing and it passed.

2021-09-13 22:07 UTC, chrisgrieser commented
Okay just to be sure, I took the `rules.ts` from your repo, redid all the necessary steps again and commited once more. I have no idea what is/was happening with those tests that changed – I literally did not touch any of those things code sections that are supposedly changed. 

Anyway, this here seems to work, all tests pass when compiling, moving footnotes to the bottom does not do anything when already at the bottom. Depending on what you think about the issue with the consecutive blank lines when moving footnotes, I think this should work (other than the tests that are changed for some weird reason.)

2021-09-13 22:56 UTC, platers commented on rules.ts
> +          text = text.replace(/\n{3,}/gm, '\n\n'); // remove blank lines resulting from ft removal
I just dont want the rule not have unintended side effects, can it only remove lines where there used to be a footnote?

2021-09-13 23:59 UTC, chrisgrieser commented on rules.ts
> +          text = text.replace(/\n{3,}/gm, '\n\n'); // remove blank lines resulting from ft removal
done

2021-09-14 00:01 UTC, chrisgrieser commented
okay, modified the moving to bottom rule, now I think everything should be fine

2021-09-14 00:10 UTC, platers approved these changes

2021-09-14 00:11 UTC, merged